apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegram-survey-bot.fullname" . }}-config
  labels:
    {{- include "telegram-survey-bot.labels" . | nindent 4 }}
data:
  record_config.yaml: |-
{{ required "env.recordConfig is required" .Values.env.recordConfig | indent 4 }}
