{{- if not .Values.env.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-survey-bot.fullname" . }}-secrets
  labels:
    {{- include "telegram-survey-bot.labels" . | nindent 4 }}
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: {{ required "env.telegramBotToken is required" .Values.env.telegramBotToken | b64enc }}
  TARGET_USER_ID: {{ required "env.targetUserId is required" .Values.env.targetUserId | b64enc }}
{{- end }}
